# Generated by Django 3.2.22 on 2023-10-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231019_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_bio',
            field=models.CharField(default='author', max_length=6000),
        ),
    ]
