# Generated by Django 3.2.22 on 2023-10-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_bio',
            field=models.CharField(blank=True, max_length=6000),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
