# Generated by Django 3.2.22 on 2023-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20231030_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorbio',
            name='author_bio',
            field=models.CharField(max_length=6000),
        ),
    ]
